[font]
size = 12.0

[shell]
program = "/bin/zsh"
args = ["-l"]

[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[cursor]
style = "Beam"

[keyboard]
bindings =[
{ key= "Back", mods= "Control", chars= "\u001b\u007f" } # Delete word
]

